name: create_release

on:
    push:
        branches: master

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master
                  fetch-depth: 0
            - uses: actions/setup-node@v1
            - name: Set env. variables
              run: |
                  echo "::set-env name=TAG_NAME::$(node -e 'console.log(require(''./package.json'').version)')"
                  echo "::set-env name=RELEASE_NAME::$(git show -s --format='%s' origin/master)"
            - uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.TAG_NAME }}
                  release_name: Release ${{ env.RELEASE_NAME }}
