name: create_release

on:
    push:
        branches: master

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  COMMIT_MESSAGES: ${{ git show -s --format='%s' }}
                  TAG_NAME: ${{ github.ref }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      Changes in this Release
                      - First Change
                      - Second Change
                  draft: false
                  prerelease: false
