name: ci

on: pull_request

jobs:
    test-some-expressions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master
                  fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: |
                  LAST_TAG=$(git describe --abbrev=0 --tags origin/master^)
                  git log --format='%s' $LAST_TAG..HEAD >> release_notes.txt
                  sed -i -e 's/^/- /' release_notes.txt
                  echo "::set-env name=RELEASE_NOTES::$(echo "Changes in this release:" ; cat release_notes.txt)"
                  echo $RELEASE_NOTES

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - run: npm build
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - run: npm test
    publish-dryrun-npm:
        runs-on: ubuntu-latest
        needs: [build, test]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm publish --dry-run
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    publish-dryrun-gpr:
        runs-on: ubuntu-latest
        needs: [build, test]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com
                  scope: "@johnyherangi"
            - run: npm ci
            - run: echo "registry=https://npm.pkg.github.com/@johnyherangi" >> .npmrc
            - run: npm publish --dry-run
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
