name: ci

on: pull_request

jobs:
    create-release-draft:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master
                  fetch-depth: 0
            - uses: actions/setup-node@v1
            - name: Set environment variables
              run: |
                  echo "::set-env name=TAG_NAME::$(node -e 'console.log(require("./package.json").version)')"
                  echo "::set-env name=RELEASE_NAME::$(git show -s --format='%s' origin/master)"

                  LAST_TAG=$(git describe --abbrev=0 --tags origin/master^)
                  echo "Changes in this release:" > release_notes.txt
                  echo "$(git log --format='%s' $LAST_TAG..HEAD)" >> release_notes.txt
                  sed -i -e '2,$ s/^/- /' release_notes.txt
                  echo "::set-env name=RELEASE_NOTES::"$(cat release_notes.txt)""
            - uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.TAG_NAME }}
                  release_name: ${{ env.RELEASE_NAME }}
                  body: ${{ env.RELEASE_NOTES }}
                  draft: true

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - run: npm build
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm ci
            - run: npm test
    publish-dryrun-npm:
        runs-on: ubuntu-latest
        needs: [build, test]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm publish --dry-run
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    publish-dryrun-gpr:
        runs-on: ubuntu-latest
        needs: [build, test]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com
                  scope: "@johnyherangi"
            - run: npm ci
            - run: echo "registry=https://npm.pkg.github.com/@johnyherangi" >> .npmrc
            - run: npm publish --dry-run
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
