name: publish

on:
    # TODO: Trigger on release events. Need to figure out
    # why actions/create-release is not sending release event
    release:
        types: [published]
#    push:
#        branches: master
#        paths:
#            - "src/**"
#            - "package.json"
#            - "package-lock.json"

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    publish-gpr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com
                  scope: "@johnyherangi"
            - run: npm ci
            - run: echo "registry=https://npm.pkg.github.com/@johnyherangi" >> .npmrc
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
